### ISSUE TITLE
Make the word "Today" in the header a prop

### ISSUE THREAD

**Issue by martinval** [richardtallent/vue-simple-calendar#101]
I'm looking into a multi-lingual use of the calendar, and it seems that "Today" in the header is hardcoded, so this is the only string that does not change when locale is changed. 
Could this be a prop that can then easily be targeted ?

**Comment by naulacambra** [comment]
Check #102 ;)

**Comment by naulacambra** [comment]
My humble thoughts on these options,
1. It makes more sense pass the prop to the header instead of the calendar (even the PR that I've made)
2. I'm not a big fan about the CSS idea. It doesn't feel right to me, since it couldn't be computed, and much more troublesome to control it.
3. I'm aware that this library is not using material design, but the [Google Material Icons](https://material.io/tools/icons/?style=baseline) library has a "today" icon ![alt text](https://material.io/tools/icons/static/icons/baseline-today-24px.svg "Today Material Icon"), and it might not be a bad idea use icons. It could be a basic either functional default representation. Also, as you mentioned, avoiding the requirement to localize the header.
4. I think this options is the one which makes more sense, with a tiny annotation, which you probably obviated, but I would like to be specific about it. Instead of display the today's month and year ("[Oct 2018]") we should display the today's unit - week, month or year - ("[7-13 Oct 2018]", "[Oct 2018]", "[2018]"). 

With all this said, if I have to pick one and only one option, I would go the 4th option. With a change in the default display. Basically, move the "Today" button at the center of the navigation controls.

| Current | Proposal |
| -------- | ---------- |
| [<<][<][>][>>][Today]| [<<][<][Today][>][>>]|

If I could choose two options, I would go for the 3rd and 4th option, letting the user pass a prop setting which one he would like to see (`icons: true | false`)

**Comment by martinval** [comment]
+1 for  moving today into the middle of the nav arrows

[<<][<][Today][>][>>]
--

**Comment by richardtallent** [comment]
I agree with the assessment, #4 sounds best. I also agree about the button placement... the current order was a holdover from when the today button was an icon, placed immediately next to the display period. (Google Calendar puts their Today button on the far left, which is another option, and perhaps less likely to be confusing once it has a label.)

The easiest way to render the label would be to use `formattedPeriod()` with the same options as the display header. My only concern is that the developer may want a more compact representation of a date range in the button than the display period.

As for an icon, I like the Material one, but we have not introduced a dependency on graphical objects so far, so I think a Unicode character or string would be preferred as a default. For example, we could use `⌖` (crosshair).

The earliest versions of this component used `↺` or `↻` for the today button, depending whether "today" was in the past or future with respect to the display period. While I think it was good to indicate the "direction" of the button, I wasn't a fan of the actual icons -- it looked too much like a "refresh" action. Here are some alternative pairs for consideration:

`⇤` or `⇥`
`⤝` or` ⤞`
`❘<` or `>❘` (similar to above, but using gt/lt to be more consistent with the other icons, though I don't care for the lack of vertical symmetry between the characters)
`⎌` (undo, could be flipped with CSS transform for moving the other direction)

**Comment by naulacambra** [comment]
> I also agree about the button placement... the current order was a holdover from when the today button was an icon, placed immediately next to the display period. (Google Calendar puts their Today button on the far left, which is another option, and perhaps less likely to be confusing once it has a label.)

Great. Should we create an issue with this "enhancement"?

> My only concern is that the developer may want a more compact representation of a date range in the button than the display period.

I'm sorry, but I don't understand this. You mean, for example, if the today's unit is `year`, the "Today" display might be represented as "01/01/2017 - 01/01/2018" instead of "2017"? And your concern would be that the developer could want a compacter representation?

> ⇤ or ⇥

This is my preferred option (after checking almost all [unicode symbols](https://en.wikipedia.org/wiki/List_of_Unicode_characters))

**Comment by GabrielMoreyra** [comment]
> Thanks!
> 
> Originally, I used CSS `content` for the button labels, which can be made multi-lingual with some static CSS with a simple selector for each language (the calendar component is decorated with a class representing the locale). However, when I split off the header component, I reasoned that since developers could now just override the header component, we didn't need properties to customize every aspect of the header (we don't have options to override the other buttons either).
> 
> That said, I agree the static text "Today" is not reasonable for a multilingual component. Here are a few options we could do, I've love to hear from anyone interested in this topic.
> 
> 1. Use a prop, as suggested here. However, if we do, it should be prop of the calendar header component, not the calendar -- the calendar component does not need this information, it would only pass it through to the slot, and I think that's not a good precedent to set. The only props the calendar should pass to the component are the ones the calendar is calculating.
> 2. Use CSS content. We can add a long list of translations with a small addition to our default CSS file, and the developer can override using CSS or a custom header. Here's a resource we could use to create the word list (this is similar to how we already handle holidays):
> 
> https://www.indifferentlanguages.com/words/today
> 
> 1. Default to an icon, not text. I did this for awhile, but never found a good icon I liked that seemed to properly represent the concept of jumping back to the current month. We use icons for the other default button labels. Like solution (1), this has the advantage of "just working" for most developers... they don't need to do anything special to have a "localized" header.
> 2. Rather than using "today," which is a misnomer anyway (we are jumping to the current month or week, not the current date), we could change the label to be the short version of today's month and year (e.g., "[Oct 2018]"). This makes it clear where the calendar will go. If we do this, we _would_ want to pass this from the calendar to the header slot, since the calendar can compute this using the current language setting. If we do this, we could add a prop on the calendar component to override the label, in case a developer wants to us the word Today, or an icon, or whatever. This has the same advantage of (1) and (3) in that it requires no extra effort to be multilingual.
> 
> Thoughts?

IMHO it would be great if you just merge the @naulacambra solution for this issue.

**Comment by richardtallent** [comment]
Update -- this will be added in 4.2.0, coming very soon... just need to do a little testing in Edge for another issue before I publish it.

**Comment by richardtallent** [comment]
Resolved in 4.2.0, just published. Please see the CHANGELOG and README for specifics on how to use the new properties.
