### ISSUE TITLE
Drag and drop events from outside the calendar

### ISSUE THREAD

**Issue by TheQuail13** [richardtallent/vue-simple-calendar#103]
If would be great if this package could (or does?) support events external to the calendar to be dragged and dropped onto the calendar, mock-up below:

![image](https://user-images.githubusercontent.com/41521881/46624532-e8fcc000-cae5-11e8-8af1-2c89da6caed4.png)

I fiddled around with this concept for a couple hours but every time I dragged an external event over, the last event that I had dragged and dropped that was already on the calendar would be the event that was placed, instead of the external event. 

Note that the following events were emitted: 
- 'drag-enter-date'
- 'drag-over-date'
- 'drop-on-date'

'drag-start' was not emitted, which makes sense since it's not part of the slotted v-for that generates the events. I'm guessing it's the blocker since the "currentDragEvent" is not being updated/set due to that.

Looking through past issues, I didn't see this come up but I imagine it would be a useful feature. Would love to hear any thoughts. And happy to provide any additional info on any of the above.

**Comment by richardtallent** [comment]
Currently, we're not using `dataTransfer.setData` for anything useful... instead, the Vue component tracks which event is being dragged using its own internal state (in `data.currentDragEvent`).

This complicates having an external drag source, since an external component can't change the calendar component's `data`.

While it would be possible to use `setData` to, say, store an event ID, that would require a non-dictionary lookup when we need to access the current drag event. This happens multiple times during the drag event.

This approach also restricts us from dragging events *off* the calendar.

We could convert `currentDragEvent` to a prop, which solves the lookup issue and the ability to set it externally, but it creates other problems:

1. We can't guarantee that an externally-set `currentDragEvent` value is an event in the `events` array. Without that guarantee, it would be easy to drop events that just disappear (because they were dragged but not put into the events array) or to accidentally duplicate events by adding them to `events` on drag. 

2. Moving it to a prop would meant that the *developer* would have to receive and respond to the `dragStart` event, rather than just letting the calendar handle it and only dealing with the drop. While the event handler would be fairly simple, it would be a breaking change and add yak-shaving code for anyone wishing to implement drag/drop.

Another tack might be to create a prop `currentDragEventId` and a `computed` property to look up the event being dragged. This solves (1), but not (2).

Perhaps the communication could happen using `dataTransfer` and an ID, with a computed lookup (on every drag event, check `dataTransfer` against an internal `currentDragEventId`, and if different, look up the event so it can be passed back in the $emit.

Or scrap sending back event objects in the `$emit` and send back the ID only, which solves the performance problem but would definitely be a breaking change, and one that, again, requires the implementing developer to do a bit more work to locate and update the dropped event.

It's late and I'm rambling now... will have to put more thought into it.

**Comment by vixper** [comment]
Hi, I implemented this feature because I need it.
I added a prop (availableEvents) where you can pass an array of available events to be dragged on the calendar.
IE:
availableEvents: [
        { title: 'Test Event 1', id: 'te1', classes: 'red' },
        { title: 'Test Event 2', id: 'te2' }
      ];

I also added a new event (dblclick-event) if you want to double click on event instead of simply click on it to call some action (like show event details)

I'm opening a pull request right now.
Bye!

**Comment by richardtallent** [comment]
The new version (4.4.0) passes the window event for the various drag/drop events it emits, so you should be able to use this to plug in the ability to drag elements from another control into the calendar (and then, on drop, you can create a new calendar item and push it into the `events` prop). Hope that helps!

**Comment by TheQuail13** [comment]
Appreciate your work on this!

**Comment by J-Ridgwell** [comment]
> The new version (4.4.0) passes the window event for the various drag/drop events it emits, so you should be able to use this to plug in the ability to drag elements from another control into the calendar (and then, on drop, you can create a new calendar item and push it into the `events` prop). Hope that helps!

@richardtallent Is there an example on how to do this exactly?

**Comment by gileneusz** [comment]
Is there an example on how to do this exactly?

@richardtallent yes, please provide any example, documentation lacks any explanation how to drop item from outside to the calendar.

**Comment by richardtallent** [comment]
There is not an example for this. If you wish to write one and submit a PR for the "example" repo that goes along with this component, I'd be happy to look at it.

**Comment by KimuraHiroDD** [comment]
I would love to see an example of creating a new task and then dragging it to the calendar control. I would appreciate it if you could create an example.
