### ISSUE TITLE
Edge, Initial Render Doesn't Show All Cells

### ISSUE THREAD

**Issue by pplusawork** [richardtallent/vue-simple-calendar#109]
I'm using Edge 41.16299.726.0, but users may have experienced the issue on other versions.  This may be more of an Edge bug, but I've only seen this behavior in this component.

On load, some of the days don't show - their events do, and it appears their cells are in the DOM, but graphically they're missing.  Doing anything to trigger a re-render causes everything to render correctly.  I normally tell the rare Edge user to just hit the Next month button then the Previous month button (i.e. go to the next month then back), which resolves it, but resizing the viewport or even mousing over the elements in the inspector will both resolve it as well (since mousing over it in the inspector will highlight the moused-over control).

I see the behavior in the demo, and other users have seen the issue as well.

Normal view, some days not rendered, but all events rendered.
![day-not-rendered](https://user-images.githubusercontent.com/13155833/47717385-9bbacc80-dc13-11e8-9a79-40af74276081.PNG)

Same as above but after a refresh with the inspector open.  Note that opening the inspector will resize the viewport and trigger a re-render, making the issue look resolved.  Refresh the page after opening the inspector to see the behavior while the inspector is open.
![day-missing-inspector](https://user-images.githubusercontent.com/13155833/47717558-15eb5100-dc14-11e8-82cf-9af35037fb9f.PNG)

Same as above, but mousing over d23 - note the whole week popped in, but not the other "missing" week.
![day-visible-inspector](https://user-images.githubusercontent.com/13155833/47717565-197ed800-dc14-11e8-86f3-f2c1c36cc37b.PNG)

**Comment by richardtallent** [comment]
Interesting... I don't have a way to test Edge (Mac at home, Windows 7 at work), but my first wild guess is that somehow Edge wants to *wrap* the rest of those "missing" weeks, and they are actually hiding below the week(s) afterward. If so, it could be a bug in Edge's metrics.

I've heard (anecdotally) of Edge also doing some weird things with metrics and ghost elements when the zoom is set to anything other than exactly 100%. Could that be the case here? Or perhaps something related to high-resolution display shenanigans?

Maybe someone else with access to Edge can see if they can reproduce?

**Comment by eventcatcher** [comment]
No, this issue is on standard resolutions and without use of zoom too (tested with BrowserStack on Edge v16 and Edge v17, vue-simple-calendar v4.1.0 and 3.0.2). In case i set the :showDate prop with a delay of 2000ms or anything like that to month before or after the current, the calendar view is fine.

**Comment by eventcatcher** [comment]
It would be helpful to have a method to redraw the calendar view, and anything like a ready event (calendar drawing in completely done), so that a redraw after first init would be possible (as a hotfix for MS Edge).

**Comment by eventcatcher** [comment]
.cv-day and position: sticky is one of the troublemakers. With position: relative the view is fine.
With min-width: calc(100% / 7 - 1px) the day tiles are fine, with position: sticky too.
But generally I think the setting of position: sticky is a problem in IE browsers.  I had different problems wit IE and sticky in the past - not only with the vue-calendar.

**Comment by richardtallent** [comment]
Apologies for not responding sooner, I've been away on business.

Using a VM, I'm testing with Windows 10 and Edge 38.14393.1066.0, and I'm not able to reproduce this issue using the current live demo app.

Manually modifying the DOM on each update is likely not the most sustainable option.

There's already a CSS hack in place to use `relative` rather than `sticky` for IE11. If that prevents the issue for Edge as well, we can add an Edge-specific position attribute.

I'm upgrading my VM now, I'll re-test after it is running the most recent version of Edge. If I can reproduce the issue, I'll see if I can come up with a CSS-only workaround that doesn't require taking the `sticky` position away for non-IE users.

**Comment by richardtallent** [comment]
I've finally been able to upgrade my VM, but it went from Edge 38 to 42, so I can't test 41, and I'm still not seeing this issue (I've changed the browser window size a few times, refreshed, etc., no problems). I can't seem to figure out how to upgrade to Edge 44 to try that one as well.

Since this appears to impact only one specific old version of Edge (or perhaps even a user-specific setting or graphics hardware), I'm reluctant to disable the `sticky` feature for all Edge users. 
Instead, in 4.2.0, I'm adding the code below, commented out, which you should be able to include in your own CSS to use relative positioning for your Edge users. 

```CSS
@supports (-ms-ime-align: auto) {
	.cv-day {
		position: relative;
	}
}
```

Once Edge-on-Chromium comes around, I'm guessing the `-ms` prefixes will no longer be supported, and sticky will return... but then it won't be a problem.
