### ISSUE TITLE
Events not showing when passed in as props

### ISSUE THREAD

**Issue by martinval** [richardtallent/vue-simple-calendar#113]
I've wrapped your calendar into a component into which I am trying to pass the events as props, but they are not showing up when I do this. 
They do show when they are defined inside the calendar, though. 
Can't figure out why this is happening.
Pls see [this codesanbox](https://codesandbox.io/s/vv19k70nw3) for reference, and thanks in advance for any help.

**Comment by richardtallent** [comment]
This is an odd one. Here's what I was able to verify:

- In the second example, if you use Date objects rather than strings, it works. So the events are being passed and the problem is in the string to date conversion.
- Passing dates as strings in the first example works, so the calendar component's ISO to date conversion is working.

This is a **guess**, I don't have time now to create an example to test this...

I think Vue's reactivity system is changing the reported data *type* of `startDate`, but only when the event objects are passed from one component's props to *another* component's props. Since Vue doesn't use proxies yet, it's using getter and setter functions, and I'm wondering if that is breaking this test:

https://github.com/richardtallent/vue-simple-calendar/blob/88a030c1e6ea338d69724850e7646947844dd3ed/src/components/CalendarMathMixin.js#L217-L219

I did a little Googling and didn't see anything pop up.

As a workaround, until we figure out the issue, I recommend supplying the wrapper component with Date objects rather than strings. You can use this same conversion function from the mixin if your source information is in string form.

**Comment by richardtallent** [comment]
**Ignore the entire last comment**

The problem is that in the second example, your dates are for January 2018, but the calendar loads for December 2018. After changing the dates in App.vue to December dates, they show up just fine. I thought I was backing up properly to January 2018 and still not seeing them, but I guess I clicked the header buttons wrong or something.

Please close and confirm, this doesn't appear to be a bug.

**Comment by martinval** [comment]
Apologies, yes of course. I shouldn't post stuff late at night...I am still having some issue that my events are not showing up after I build my project, need to look elsewhere...

**Comment by martinval** [comment]
OK, sorry to waste your time on these last 2 issues.  
It turns out that I wasn't setting my tasks when the component was created, but failed to realise that because they were pulled in from the persisted store state....taking the opportunity to thank you for this great little calendar
