### ISSUE TITLE
Day Slot not working

### ISSUE THREAD

**Issue by benjamin79** [richardtallent/vue-simple-calendar#122]
Hi,

having 

```
      <calendar-view :show-date="showDate" @show-date-change="setShowDate" class="theme-default" :display-period-uom="displayPeriodUom" :showEventTimes=true :startingDayOfWeek=1 :events="events" @click-event="dox" >
        <calendar-view-header
        slot="dayHeader"
        index="0"
        label="XXX" />
      </calendar-view>
```
leads to an error:
Duplicate presence of slot "dayHeader" found in the same render tree - this will likely cause render errors.

Not sure if it is me or a bug.

thanks

p.s why not a simple array for the label of the day header like ["Mon", "True", ...]

**Comment by richardtallent** [comment]
The `calendar-view-header` component is for the `header` slot (the one containing the navigation and description of the viewed period), not the `dayHeader` slot (which renders the names of the days of the week).

The `dayHeader` slot is only really intended for *very rare* situations where someone needs to fully replace the *markup* for the days of the week header, not just to change the day labels.

For the day labels, the component is designed to use the *user's* language by default. Allowing an array of weekday names would encourage a suboptimal choice of the programmer forcing their own language on the user. Instead, we use the standard `Intl` API to display an appropriate name in the user's language (it does this with the name of the month in the header). We're lucky to live in 2018, where this is all native to the browser instead of requiring some huge JavaScript library like moment.js! :)

The `weekdayNameFormat` prop allows you to decide whether you want a shorter name or a longer one, and simple CSS will allow you to, for example, force those values to upper or lowercase. The default is short, which, for English users, gives the values you mentioned.

If you need to force the UI to English (not recommended), you can use the `locale` prop, which will override the browser's language setting.
