### ISSUE TITLE
Event popout module

### ISSUE THREAD

**Issue by g1robo** [richardtallent/vue-simple-calendar#124]
Does this come out of the box with side dropdown menus for selecting month, day, year, adding event, etc? 
I added this code to the app and I only have the calendar
![image](https://user-images.githubusercontent.com/11168633/56007136-b060bd80-5ca5-11e9-91bf-a04f5e489c40.png)

**Comment by g1robo** [comment]
navigation buttons at the top are not functional either

**Comment by richardtallent** [comment]
Hi, thanks for checking out my component!

Vue has a philosophy of "props in, events out" that may feel a little unfamiliar at first, especially if you're coming from the world of JQuery, where components tend to be "kitchen sinks" that are complete applications in an of themselves.

The idea of Vue, basically, is that each component should only *show* property data passed to it, not *change* that data. If a user performs some action in the component that suggests that a change *should* happen (such as clicking a button), the component sends an Event to the parent component/page that "owns" the data, and the change is made in the parent, if appropriate. The modified data goes back to the component via its props, and the component updates the DOM.

Even within this library, there are two *separate* components--the header and the calendar. Your app is responsible for receiving events from the header, and using them to manipulate the state of the calendar. They don't "talk" to each other directly. (You can see this in the sample code in the README and in the more complete sample app in the other repo.) By decoupling these components, developers can easily drop in custom headers if my default header doesn't work for their use case (headers tend to be very taste-specific anyway).

This also allows developers to "trap" events and apply business logic before any data is changed. For example, you might not want someone to be able to navigate more than, say, 4 months into the future. Or every time someone navigates, you may need to request more data from your database before you change the view. Since the calendar doesn't change its own data, your app has the opportunity to control what happens.

With this philosophy in mind, the goal of this component is simple: create a 7-day grid for a given set of weeks or months, and display, floating above that grid, any calendar events passed to it. That's it. It's not going to talk to your database to get the events, navigate between months for you, or provide a UI for users to add new events. All of those tasks would be far too different from one application to another to try to work into a single component anyway.

Consider the "add event" form, for example. What fields should a New Event form have? The calendar just needs a unique ID, a title, and date range, but if you're creating an actual calendar event in some real-world application, you may want the user to be able to provide a number of other event details, and each detail is going to be specific to your app. One developer may be a plumbing company scheduling visits, another might be a school trying to publish the cafeteria menu, and those "add event" forms are going to look and function very differently.

Hope that makes sense! Sorry for the length, it's late here and I don't have time left tonight to edit it down to something shorter.
