### ISSUE TITLE
BUG: Highlight color disappears in week view

### ISSUE THREAD

**Issue by jusvu** [richardtallent/vue-simple-calendar#126]
Sw version: 4.2.1
Steps to reproduce the problem:
1. Navigate to https://www.tallent.us/vue-simple-calendar/
2. Change Period UOM to "week"
3. Today is highlighted (yellow color)
4. Click next or previous week button
5. Click Today button -> Today highlight color is disappeared
There's no problem with the steps above if the selected Period UOM is "month"

**Comment by richardtallent** [comment]
Confirmed, there is an edge case here!

The issue is due to the CSS for the class `outsideOfMonth` taking precedence over the css for `today`. It's showing up in the Week view because this _week_ starts in April, so May 1 is "outside" of that month.

I've resolved this in the CSS and updated a few dependencies, it is now published as v.4.2.2.

Thanks!

**Comment by jusvu** [comment]
Wow, this was super fast fix! Thanks, I'll try with 4.2.2
