### ISSUE TITLE
Delete event on calendar?

### ISSUE THREAD

**Issue by kieugol** [richardtallent/vue-simple-calendar#140]
Hi Author,

I tried finding remove event on the calendar.
Seems it's not available.
If that feature is available, pls show me guideline how to config them?

Thanks a lot!

**Comment by richardtallent** [comment]
Since this is Vue, the calendar component shows the events _you provide_ in the events property. If you remove an event from that array, the calendar component will update automatically. If you aren't familiar with how reactivity in Vue works, here's a good resource to start with:

https://vuejs.org/v2/guide/

The calendar component has no built-in UI for deleting events. You would need to provide. Most online calendars implement something where when you click on an event (this click is passed back by the component to your page), a panel or dialog shows the event details and offers options to edit, delete, etc. That sort of panel is outside the scope of this component.
