### ISSUE TITLE
Week numbers

### ISSUE THREAD

**Issue by narkoze** [richardtallent/vue-simple-calendar#145]
Is it somehow possible to add week numbers?

**Comment by richardtallent** [comment]
Yes, it would be possible. It would require adding additional markup to each week to hold the number, and to readjust all of the other widths. There would also need to be several options added for computing the week number, since there is more than one way to number a week on a calendar. I could imagine there could also be a need for numbering multi-week numbers (pay periods, sprints, etc.).

I'll add this to the potential feature set for the next version.

**Comment by richardtallent** [comment]
This feature has been added to the current code for version 5.0.0.

This is in the master branch, I'm fairly close to releasing it (within the week I believe). If you have a chance, please take a look at this and see if it would provide you either the default functionality or the extensibility needed to fit your use case.

**Comment by richardtallent** [comment]
Added in version 5.0, just published
