### ISSUE TITLE
Summer time transition causes item to span 2 days

### ISSUE THREAD

**Issue by robert-joscelyne** [richardtallent/vue-simple-calendar#150]
Using Demo for vue-simple-calendar 4.3.2, adding an item for 31 March 2020, 1 April 2020 or 2 April 2020 all result in an item that is displayed as spanning two days. Only appears to happen on days near the month transitions.

The behaviour is present in the latest versions of Firebox and Chrome. 

Checked previous issues and found someone reporting a similar bug in #29 but resolution was described as Time Zone related but not specific on how to resolve the problem. Thanks
![vue-simple-calendar20200319a](https://user-images.githubusercontent.com/3079469/77114596-ae11f200-6a24-11ea-9a95-da888e8c20f5.png)

**Comment by richardtallent** [comment]
HI Robert,

There's no resolution yet, because I can't reproduce this issue. I'm testing on Chrome on a Mac, and I've flipped through a bunch of time zones on my computer. If you can provide more details about your test environment (time zone, localization settings, browser, and OS), I may be able to reconstruct the issue.

I do know that the demo app passes the start and end dates to the calendar component as an ISO-date string, so identical values in those fields should result in a single-day result. So I think it's something else going on in the core component code, not the demo itself.

**Comment by robert-joscelyne** [comment]
Hi Richard,

Thank you for taking the time to look at the issue. 

I have been working on it and now understand that the issue happens when there is a Summer Time/Day Light Savings transition during the week being shown. I am based in the UK and so Summer Time starts here on 29 March.

The problem seems to be in the dayDiff calculation where the  weekStart is UTC and the startDate after the start of summer time is now BST(UTC+1). When setUTCHours is then used to zero the time component this causes the change of date impacting the offset and span calculation.

Would using the Date.UTC method and removing the setUTCHours resolve this?
