### ISSUE TITLE
Hungarian day names are in wrong order

### ISSUE THREAD

**Issue by rrd108** [richardtallent/vue-simple-calendar#151]
The day names are in wrong order in Hungarian.

Theye are Sze, Szo, K, P, H, Cs, V now, what is Wednesday, Satrurday, Tuesday, Friday, Monday, Thursday, Sunday

Can you reorder them? the proper order is H, K, Sze, Cs, P, Szo, V

**Comment by rrd108** [comment]
Hmm it seems when I use `startingDayOfWeek="1"` I run into this error, but if I use binding, like `:startingDayOfWeek="1"`, than I get the right order.

**Comment by richardtallent** [comment]
Hi @rrd108,

Yes, with Vue components, numeric props (like `startingDayOfWeek`) require binding. It will throw a warning for you about this in the Console.

The weekday names you were seeing were a result of Vue passing the prop as a string "1", which caused the loop in `getFormattedWeekdayNames` to perform string concatenation for days 1-7 instead of addition. This resulted in 11, 21, 31, 41, etc., which, modulo 7, yields 4, 3, 6, etc., which were then passed to the `Intl` class and came back as the strange day name order.
