### ISSUE TITLE
Can't use the new item slot

### ISSUE THREAD

**Issue by benjivm** [richardtallent/vue-simple-calendar#161]
Hello, I'm not sure what I'm doing wrong trying to update to the newest version:

```js
<calendar-view
        :items="events"
        :show-date="showDate"
        class="theme-default holiday-us-official wrap-item-title-on-hover"
        @click-date="onClickDay"
    >
        <div
              slot="item"
              :key="item.id"
              slot-scope="{ item, top }"
              :style="`top:${top}`"
              :value="item"
              :class="item.classes"
              :title="item.title"
              class="cv-item"
              @mouseenter="onMouseEnter(item, $event)"
              @mouseleave="onMouseLeave(item, $event)"
              @click.stop="onClickEvent(item, $event)"
              v-html="item.title"
         />
</calendar-view>
```

I am getting `[Vue warn]: Error in render: "TypeError: item is undefined"`. Perhaps the issue is the passing by `value`, do I need to iterate over the events and have a custom slot for each?

**Comment by richardtallent** [comment]
Hi @benjivm,

I'm currently using Vue 2.6.12, which uses the newer "scoped slots" syntax to pass information to your slot implementation (see https://vuejs.org/v2/guide/components-slots.html). With this approach, the following "slot props" are available to your "item" slot:

- value (the normalized calendar item)
- weekStartDate (the first date of the week the item is being rendered to)
- top (the computed pixel offset of the item from the top of the week's grid)

#### Reference:
https://github.com/richardtallent/vue-simple-calendar/blob/6dc02e1cfe58d88af6ce26f9032d5ec0fc440a4e/src/components/CalendarView.vue#L101

#### The fix?

The name of the slot you're implementing (item) is passed as the *modifier* for `v-slot` (rather than as the value of a `slot` attribute), the props available to your slot are passed to an object whose name you choose, and the calendar item object is available through that object (under the `value` key).

I haven't tested this (slots still confuse me from time to time, so I could be wrong), but I believe this is the syntax you'd need (rename `myItemSlotProps` to your preference):

```js
        <div
              v-slot:item="myItemSlotProps"
              :key="myItemSlotProps.value.id"
              :style="`top:${myItemSlotProps.top}`"
              :value="myItemSlotProps.value"
              :class="myItemSlotProps.value.classes"
              :title="myItemSlotProps.value.title"
              class="cv-item"
              @mouseenter="onMouseEnter(myItemSlotProps.value, $event)"
              @mouseleave="onMouseLeave(myItemSlotProps.value, $event)"
              @click.stop="onClickEvent(myItemSlotProps.value, $event)"
              v-html="myItemSlotProps.value.title"
         />
```

Or, using destructuring to remove the need for the `myItemSlotProps` parent object:

```js
        <div
              v-slot:item="{ value, top }"
              :key="value.id"
              :style="`top:${top}`"
              :value="value"
              :class="value.classes"
              :title="value.title"
              class="cv-item"
              @mouseenter="onMouseEnter(value, $event)"
              @mouseleave="onMouseLeave(value, $event)"
              @click.stop="onClickEvent(value, $event)"
              v-html="value.title"
         />
```

Or, destructuring, and renaming `value` to `item` if that works better for you:

```js
        <div
              v-slot:item="{ value: item, top }"
              :key="item.id"
              :style="`top:${top}`"
              :value="item"
              :class="item.classes"
              :title="item.title"
              class="cv-item"
              @mouseenter="onMouseEnter(item, $event)"
              @mouseleave="onMouseLeave(item, $event)"
              @click.stop="onClickEvent(item, $event)"
              v-html="item.title"
         />
```

Since the old syntax is deprecated for 2.6+ and is removed in 3.0, even if there is a way to still make `slot-scope` work (maybe with `i` instead of `item`?), it's probably best to go ahead and move to the new syntax.

I'll keep this open until you can confirm that this resolves your issue...

**Comment by benjivm** [comment]
@richardtallent Thanks for the awesome answer! I'm on the right track now. Initially when I tried your suggested code I received an error: `v-slot can only be used on components or <template>`, so I moved the `v-slot:item` onto a parent `<template>`:

```js
<template v-slot:item="{ value: item, top }">
    <div
        :key="item.id"
        v-tooltip="{ content: item.originalItem.tooltip, placement: 'top' }"
        :style="`top:${top}`"
        :value="item"
        :class="[item.classes, { 'isHovered' : currentHoveredEventId === item.id }]"
        :title="item.title"
        class="cv-item"
        @mouseenter="onMouseEnter(item, $event)"
        @mouseleave="onMouseLeave(item, $event)"
        @click.stop="onClickEvent(item, $event)"
        v-html="item.title"
    />
</template>
```

The next issue I encountered was that the icons I am using in event's `v-html` are breaking display. I figured out that it's because of the self-closing tags: changing the icon HTML from this `<i class="fad fa-caret-circle-right"/>` to this `<i class="fad fa-caret-circle-right"></i>` fixes the display, though it seems likely this problem has nothing to do with your library.
