### ISSUE TITLE
Add vacation days and dates

### ISSUE THREAD

**Issue by fadisharif15** [richardtallent/vue-simple-calendar#162]
Hello @richardtallent
 I would like to inquire about the possibility of adding vacation days and dates to the calendar.
For example, if Friday is a holiday, it appears in a different color and days cannot be added on it. The same applies to dates as well

**Comment by richardtallent** [comment]
Hi @fadisharif15 ,

You can use the `dateClasses` prop to pass through a set of specific dates to apply your own CSS class or classes to them:

```html
<calendar-view ... :date-classes="{ '2020-10-27' : 'my-vacation-class' }">
...
<style>
.my-vacation-class {
  background-color: #FFE7E7;
}
</style>
```

If you want to change the style of *every* Friday, you can just override the `` class (example here for a Sunday-based calendar):

```css
.dowX {
  background-color: #FFE7E7;
}
```

If you want to apply a special color to a `item` (aka event) rather than to the grid cell representing dates, pass a `classes` property in the item with the CSS class it should use, or a `style` property with the CSS string to apply in its style. 

If you want to change the style of specific dates regardless of the year (holidays, for example, or days that happen the same relative date each year), you can use CSS directly as well. Check out the `holidays-us` theme here to see examples of how to do this:

https://github.com/richardtallent/vue-simple-calendar/blob/main/static/css/holidays-us.css
