### ISSUE TITLE
Navigate calendar using mouse scroll

### ISSUE THREAD

**Issue by mirkoperillo** [richardtallent/vue-simple-calendar#170]
It would be great to navigate periods (backward and forward) using the mouse scroll

**Comment by richardtallent** [comment]
Personally, I would not want such an option. I use an Apple Magic mouse, which has a fairly "touchy" scroll action on it, rather than a traditional wheel mouse with incremental scroll positions.

Also, the weeks themselves already have a scroll action defined -- it scrolls the events when there are more events to display than can be displayed in the grid.

I recommend overriding the header and attaching your own scroll event handlers for the contents there, and use that to modify the dates shown.

**Comment by mirkoperillo** [comment]
> I recommend overriding the header and attaching your own scroll event handlers for the contents there, and use that to modify the dates shown.

Thank you for your suggestion. I will try to implement it
