### ISSUE TITLE
Week View

### ISSUE THREAD

**Issue by houseoftech** [richardtallent/vue-simple-calendar#23]
Here's a possible [layout for a week view in flexbox](https://codepen.io/houseoftech/pen/mqwWxo?editors=1100).

**Comment by richardtallent** [comment]
Hi... I’m at a pretty intense workshop and haven’t had any time to look at this, but will as soon as I can!

**Comment by richardtallent** [comment]
This is intriguing...

As a first step, I'd suggest we make some adjustments to the current code:
- Test to ensure events with time of day don't have display bugs (like the DST issue).
- Provide a mechanism for optionally prefixing event titles with a formatted time.
- Move to using SASS or CSS variables, like you've done here. I would lean toward CSS variables since I have to drop IE11 support soon (losing my ability to test on it) and it would be nice to not add another build dependency, but I'm open to either one.

With these changes, I think it would be relatively trivial to add a "week view" to the current component that doesn't have the timetable grid, but that is more compact and shares the same component codebase.

Adding a timetable view to the current component *might* complicate it too much, but with the prework above done, we could extract a functional component with shared logic and then have two separate components for a month / compact week view and a timetable view (with a configurable number of days to show--one day, work-week, full-week, etc.).

**Comment by Hellowor1d** [comment]
@richardtallent 
sincerely expect your week view calendar, too~ 💯  😄

**Comment by richardtallent** [comment]
@houseoftech, I created a "poor man's" week view in version 2.0. No time grid, I just abstracted the view enough to support any showing the weeks for any number of week, month, or year periods. Showing of times is also now supported.

@Hellowor1d, thanks! The "week" view has been released, you can see it in the demo app. Yes, I like FullCalendar, it was one of the inspirations for this component, though it does a lot more than I want to do, and I wanted something that was Vue-native with no JQuery dependencies.

Closing this for now... I'll reopen if I have a use case in the future for an "agenda" / time grid version of the weekly view. At this point I think adding it would complicate the logic of this component too much, but a separate component could be created that shares a good chunk of the logic and interface.
