### ISSUE TITLE
Do you need IE11 support?

### ISSUE THREAD

**Issue by richardtallent** [richardtallent/vue-simple-calendar#25]
In planning future revisions, I'm considering dropping official IE11 support for the following reasons:

- It has a very small user base now--mostly within corporate IT environments that likely aren't progressive enough to be using Vue anyway.
- My own way of testing IE11 will be disappearing soon, and I'm not eager to set up special systems to do so.
- IE11 does not support CSS variables, and using variables would streamline our styling. We could use SASS, but I usually prefer native functionality where possible.
- IE11 flexbox support is buggy and outdated.

So, for anyone using this component, what's your situation around the need for IE11 support?

[![](https://api.gh-polls.com/poll/01C04CWHQ6TSPXQB3J7NQP9Q1X/I%20need%20IE11%20support%20for%20the%20foreseeable%20future)](https://api.gh-polls.com/poll/01C04CWHQ6TSPXQB3J7NQP9Q1X/I%20need%20IE11%20support%20for%20the%20foreseeable%20future/vote)
[![](https://api.gh-polls.com/poll/01C04CWHQ6TSPXQB3J7NQP9Q1X/I%20need%20IE11%20support%20for%20the%20next%206%20months)](https://api.gh-polls.com/poll/01C04CWHQ6TSPXQB3J7NQP9Q1X/I%20need%20IE11%20support%20for%20the%20next%206%20months/vote)
[![](https://api.gh-polls.com/poll/01C04CWHQ6TSPXQB3J7NQP9Q1X/I%20don't%20need%20IE11%20support%2C%20new%20standards%20FTW!)](https://api.gh-polls.com/poll/01C04CWHQ6TSPXQB3J7NQP9Q1X/I%20don't%20need%20IE11%20support%2C%20new%20standards%20FTW!/vote)

**Comment by richardtallent** [comment]
Looks like we keep IE11 support for now!

**Comment by phil-w** [comment]
I note that my own stuff built on this doesn't work with IE11.... nothing obvious in my console to tell me why. I checked the demo page and... I reckon IE11 stopped working sometime after November. As my own usage is for "our own people only" I can tell them to use a decent browser, so I'll not bother to work out what's broken or fix it, but I will add in a message so it doesn't confuse me when I'm testing.

So I reckon that's a :

"I don't need IE11 support because this page is only used by people at whom I can yell they're being stupid".
