### ISSUE TITLE
One Event Will show two events on Calendar.

### ISSUE THREAD

**Issue by MarsZone** [richardtallent/vue-simple-calendar#33]
I just input one event. but it show two events on calendar.
I don't know why.
<img width="452" alt="bug1" src="https://user-images.githubusercontent.com/3784198/34455395-5996fd36-edb9-11e7-9f2b-fc4f535ebdb2.png">
<img width="307" alt="img2" src="https://user-images.githubusercontent.com/3784198/34455405-86c617e2-edb9-11e7-8d76-41ae87b387a8.png">
<img width="378" alt="img3" src="https://user-images.githubusercontent.com/3784198/34455407-8f458f4c-edb9-11e7-89e6-584dfaf156d4.png">

If I give the endDate it will be normal.

**Comment by MarsZone** [comment]
By the way it's not very good looking at mobile device which i want to use this for my web-apps development.So will it be a way to look better on mobile?

**Comment by richardtallent** [comment]
Thanks for the bug report! I found the issue, it was a logical problem when `endDate` was not provided. Released version 1.8.2, which fixes this issue.

Displaying text in a 7x6 grid on a small mobile device is always going to be a problem. Changing the font family (to something not as wide as the screen shot above--is that Roboto?) and font size of the parent will help squeeze more text in. With default fonts, the calendar is actually usable even on portrait mode on my iPhone 7 and X. Granted, those are rather large phone screens.

I have a similar need coming up, and have considered doing what other mobile-sized date pickers do--show the date only in the cell, click the cell, and a pop-up window shows the events. However, since the markup would be so different, it's very likely I'll build it as a separate component. Also, there are a number of great Vue-friendly date pickers already out there that could be used for this.

You *could* actually accomplish this with the current calendar component, but to do it, you'd need to *not* send it the `events` property. Instead, have your parent control respond to the `clickDay` event and use that to populate a list of events for that date (using a dialog box or whatever). The tricky part would be to have the component show "empty" days differently that those that have events. For that, you could sent a single event for each date that has *any* events, but with a very short title (perhaps just an icon) and respond to the `clickEvent` event as well as `clickDay` to show the events.

But for now, the component is primarily intended for desktop and tablets.

**Comment by MarsZone** [comment]
Thank you so much! You are a very efficient person. And very great project.
OK I know it, so I need upgrade to 1.8.2 right?
Second, so I can smaller the font size will be better. Infact I think maybe I can use icon instead.
So , it's good news that you consider to make a mobile-sized one. But I think it can be later and how about make this project can drag and drop on the mobile first? 

Yes, what you say accomplish by handler the clickDay event and show the list is very good advice.
Maybe I try it later.

Again,Thanks to you fast replay.

**Comment by richardtallent** [comment]
You're welcome! Yes, you'll need to upgrade to 1.8.2.

Yes, making drag and drop work on mobile is already an open issue, and one I hope to resolve soon. I'm happy to have help from anyone more familiar with mobile touch events.
