### ISSUE TITLE
Wrong Positions locate.

### ISSUE THREAD

**Issue by MarsZone** [richardtallent/vue-simple-calendar#34]
I set a date:startDate:'2017-12-28',
and it show the event at 29.
<img width="306" alt="img4" src="https://user-images.githubusercontent.com/3784198/34455504-91449fc0-edbb-11e7-9780-887938d5114c.png">

**Comment by richardtallent** [comment]
Hi @MarsZone,

When you provide a string date to JavaScript in ISO 8601 form (`yyyy-mm-dd`), JavaScript interprets it as midnight UTC. It then converts it to the local time zone of the browser, and the calendar uses the **local** year, month, and day of that date(ignoring the time and time zone) for display.

So, when you use `2017-12-28`, the calendar component doesn't necessarily see December 28, it sees the 27th, 28th, or 29th, depending where the user is located, and also sees a time component that resulted from the time zone conversion (which it ignores).

Because of this, dates should be provided as Date objects (*e.g.*, `new Date(2017,11,27)` for December 27--be sure to use a 0-based month).

One thing I think I'd like to do is change the component to *not* let JavaScript convert strings to dates automatically, and to instead do its own conversion when `startDate` or `endDate` are provided in a simplified ISO string form (basically modifying the `dateOnly` method and using `map()` along with `filter()` in `getWeekEvents()` to convert the dates once for each event). I think that will be necessary if we're going to support events times in the future (which I'd like to do).

**Comment by richardtallent** [comment]
See this SO answer for more details on the problems of using strings for dates:
https://stackoverflow.com/questions/33908299/javascript-parse-a-string-to-date-as-local-time-zone

**Comment by MarsZone** [comment]
Very useful. I got it.
I just use new Date(2017,11,27) give the date objects to startdate.
It works fine and you may provide the options(eg. like different date format) to chose if convert to UTC time or not?
