### ISSUE TITLE
Agenda/Time Grid/Week View

### ISSUE THREAD

**Issue by blalan** [richardtallent/vue-simple-calendar#47]
I am in need of this feature. I saw your notes on this issue #23 and see that you are interested in seeing a use case:
Online Time Tracker - Adding time to projects/jobs, then being able to see how/where time was spent, where you were able to multi-task (multiple columns where same day/time), as well as see "dead space" where you don't have any time logged.

**Comment by richardtallent** [comment]
Now that there's a week view, I do think an "agenda" view is remotely possible. However, it would require more effort than I have time for at the moment. I'll sketch out a few of the steps that would be needed. For sanity, I'm assuming below that support would be limited to *single-day* events with timespans.

First, I need to refactor the CSS classes before adding much in the way of additional features. This is slated for 3.0, and will make theming easier.

The majority of work would be in the **slot assignment** code. (Note that the word "slot" here has nothing to do with Vue slots, I need to come up with a less loaded term as part of said CSS refactor.)

Currently, up to 20 vertical slots are allowed for each day, and they are assigned solely based on stacking the events.

Instead, first the renderer would need to assign all-day (no start or end time) and multi-day events as it does now, so those would appear at the top and could continue to span more than a single day.

Next, it would need to *dynamically* assign slots as it renders each *single-day, timespan* event -- say, a different slot for each 30-minute span between a configurable start and end time.

Support would need to be added for an event to have both a slot *number* and a slot *height*, so timespan events can have a height that matches their timespan (rounded to the nearest interval).

Next, support would need to be added to allow events to run in parallel on the same day. This would require adding a more nuanced slot number and width--say, allowing up to 6 events to occur in parallel (overlapping in at least one time segment) each day. I'm picking 6 here because it's evenly divisible by 1, 2, and three--the most common use cases--allowing those cases to evenly divide the width.

The grid would need to be adjusted to be prefixed with a header column to show the times. That's probably the easiest change, but there are some difficulties, like positioning the labels and dealing with events falling outside the slotted times.

Additional markup would need to be added to provide thin borders and drop zones for each time interval. This would be tricky, because each day in the week would need its own markup so the drop zone is specific both to a certain day and time. The drag and drop code would need to be changed to use these time slot drop zones.

Ideally, support would need to be added to provide a "drag bar" on the top and bottom of each event to allow the user to change the timespan.

As you can see, this would be a significant amount of work, and one that would really only make sense for a one-week view (unless you have a massive display). That's a lot of additional code, markup, and CSS that wouldn't benefit the **primary** use case of this component (showing a calendar *month*). 

That's why I'm still thinking it would be better for an agenda view to be a separate component. It may be possible to extract certain pieces of this component's code (such as events) in a way that both components could share them, and certainly they could share the config and events API, many CSS classes, etc.

**Comment by blalan** [comment]
Thank you for the comprehensive outline. I'll try and take a look more into this component, and see if I can't help with a solution. I also found this chart 'library', bar graph that might spark some inspiration. [Echarts](https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-waterfall2)

**Comment by richardtallent** [comment]
Closing this issue -- the more I think about it, the more I'm convinced that if someone wants a time-agenda view, it should be a different component. It would require far too much logic and markup that would be specific only to that view.
