### ISSUE TITLE
Release 2.2.1 on npm

### ISSUE THREAD

**Issue by pelletiermaxime** [richardtallent/vue-simple-calendar#59]
Hi,

First of all, great plugin! 
Could you please release 2.2.1 on npm to make it easier to install for those of us that need IE 11 support ?

Thanks!

**Comment by richardtallent** [comment]
I'd be happy to, but I haven't actually been able to test to see if the 2.2.1 fix worked, because I don't have easy access at the moment to IE11. Would you have time to clone the repo and test it?

**Comment by pelletiermaxime** [comment]
We tested it and it seems to somehow work even less... all there is in the console is something like " Expected ':' ".
What we did is yarn add https://github.com/richardtallent/vue-simple-calendar#2.2.1 and then we did "npm install" and "npm run build" in node_modules/vue-simple-calendar.

**Comment by richardtallent** [comment]
I played with it a little tonight, no luck yet. I'm not sure if the problem is webpack4-specific or if something is amiss in my config. A complicating factor is that my sample/test app is in a different repo (on purpose), and apparently Babel won't transpile files imported from a path outside the repo being built. This is making it pretty much impossible to test. I'm sort of at a loss at this point. Really need something who has a far better understanding of Babel and webpack to look at the configuration.

**Comment by richardtallent** [comment]
I'm really slammed at my day job at the moment, but giving a quick update that I've been playing with vue-loader 15 at work, and I think it may be part of the solution for getting transpiling working properly. Just haven't had time to try. Open to PRs if anyone is waiting on this...

**Comment by richardtallent** [comment]
Resolved IE11 issues in 3.0, about to release. 2.2.1 will be skipped on npm.
