### ISSUE TITLE
Get start and end period of calendar

### ISSUE THREAD

**Issue by teddy-dubal** [richardtallent/vue-simple-calendar#68]
Hi , thanks for you works
I want to known if it's possible to get start and end period of displaying calendar ?

**Comment by richardtallent** [comment]
Hi Teddy,

Since Vue doesn't provide a way to pass computed properties or methods back to the parent (other than with an event), there's no *direct* mechanism for this. However, there are a few indirect ways you can do so:

1. If you use the `headerSlot` slot to create a custom header, it receives the `headerProps` property from the calendar, which includes this information in the `periodStart` and `periodEnd` keys.

 2. You can include the `calendar-mixin.js` mix-in in your parent, which is what the calendar component uses for date math, and compute these values the same way the calendar component computes its `periodStart` and `periodEnd`.

3. You can use a `ref` to hack through Vue and obtain these computevalues from the parent component. However, as this article describes, you'll need to set up a `watch` to make it reactive:
https://medium.com/@konafets/accessing-computed-property-of-child-component-in-vuejs-95b5ade29a1c

Awhile back I thought of having the `show-date-change` event pass this information, since I know it's needed to, for example, give the component a list of matching events. I didn't end up doing so for several reasons:
1. This event isn't raised on mount, so the parent still has to figure out the date range for the first calendar period shown.
2. Passing it back in the event payout would be a major breaking change, impacting every user.

I'm open to suggestions. Unfortunately, Vue's "props in, events out" model isn't a perfect fit for components with complex inner logic.

**Comment by teddy-dubal** [comment]
Hi Richard 

Thanks for your answer , i will try the second way.

Thanks you.

You can close my issue if you want

**Comment by richardtallent** [comment]
Good luck! I'll close this and open a related question for the broader community.
