### ISSUE TITLE
Getting previous day when parsing date

### ISSUE THREAD

**Issue by manelmendez** [richardtallent/vue-simple-calendar#81]
When I click on some day in the calendar I get that day (e.g Fri Jul 20 2018 00:00:00 GMT+0200 (Central European Summer Time)) but when I send this data to another view or to the database (to save it) I get the previous day (2018-07-19T22:00:00.000Z).

I'm going to attach some images with the problem:

Date I click:

<img width="331" alt="date" src="https://user-images.githubusercontent.com/10993997/42751874-804cf088-88ec-11e8-8b60-620cb47e4ee4.PNG">

Error I get:

<img width="275" alt="error" src="https://user-images.githubusercontent.com/10993997/42751883-87330f7c-88ec-11e8-818c-e934f466f5f9.PNG">

I searched this in other issues but I don't know if this is normal or is resolved in another issue.

Thanks for the help!

**Comment by molobala** [comment]
This is timezone problem. I was getting the same issue. By default dates are based I think on GMT, so if you are o  GMT+1, you will have this behavior.

**Comment by manelmendez** [comment]
@molobala hi, thanks for answer! And do you know how to fix it?

**Comment by richardtallent** [comment]
Time zones are a particularly tricky problem with web applications. There are at least three time zones to worry about: the browser, the app/database, and the event.

`CalendarView` uses the **browser's** local time zone when parsing strings into dates and when emitting dates in events, so the `click-date` event is going to pass the date the user selected as that date on midnight of the browser's time zone.

The two dates you're seeing (2018-07-20 00:00 CEST and 2018-07-19 22:00 UST) are the *same instant in time* (1532037600000 milliseconds since the Epoch), but two "logical" dates.

If your other logic uses UST but needs to see the same logical date (*i.e.*, the same year, month, and day number), you'll need to time-shift the date emitted by CalendarView to UST. Something like the following:

```HTML
<calendar-view @click-date="onUserClickedCalendarDate" />
```

```JavaScript
onUserClickedCalendarDate(userDate) {
  const shiftedDate = new Date(userDate.getTime() - userDate.getTimezoneOffset() * 1000 * 60)
   (... do things with the new date)
}
```

Just don't pass this shifted date *back* to the calendar as a JavaScript Date object, or you could see the same problem in reverse. All dates going into `CalendarView` should either be shifted to the user's local time zone, or should be passed as ISO 8601-format strings that include no time zone information -- CalendarView will interpret them as that date/time according to the user's time zone).
