### ISSUE TITLE
Dates do not scroll independently

### ISSUE THREAD

**Issue by lochstar** [richardtallent/vue-simple-calendar#83]
Hi, just wondering if this is by design or an oversight. Ideally each date would scroll independently. See the following GIF for an explanation: https://imgur.com/a/zXJP0Sd

**Comment by richardtallent** [comment]
Hi,

Yes, it's intentional behavior. One of the core features is the ability to have events that span more than one day. This requires the container element for the events to cover the entire week, not individual days, and it's that container that is scrolling (*i.e.*, the events float on *top* of the calendar grid, they aren't rendered inside the individual grid cells).

For use cases where events *never* span more than a day, I can see how that might be suboptimal, but limiting events to a single day and then scrolling the days individually would require a significant rewrite of the markup.

I can imagine an alternative layout where events would be rendered into 7 different partially-overlapping overlays (with `overflow-x: visible`), depending on their "start day" for the week, rather than a single overlay and a `left` position. That would allow scrolling each overlay independently and achieve the effect you're wanting. But if someone had any multi-day events, it would lead to some really weird effects where events would overlap one another as the user scrolls.

**Comment by lochstar** [comment]
Makes sense, thanks for the clarification.
