### ISSUE TITLE
Events still show in outsideOfMonth cv-days

### ISSUE THREAD

**Issue by johnhorsema** [richardtallent/vue-simple-calendar#84]
How to disable showing events in outsideOfMonth day cells?

I tried with some css to hide them but doesn't really work.
```
.theme-default .cv-day.outsideOfMonth + cv-event {
	display: none;
}
```

**Comment by johnhorsema** [comment]
Attached screenshot for illustration
<img width="1224" alt="screen shot 2018-07-26 at 4 22 34 pm" src="https://user-images.githubusercontent.com/10090182/43250550-35fe4fd4-90f0-11e8-9314-88dbe0040ca2.png">

Would like events "same day" and "test" to be hidden

**Comment by richardtallent** [comment]
Events are drawn *above* the days, not within them in the DOM (a key requirement for allowing events to span multiple days), so there's no simple CSS selector solution for this.

The best solution would be to simply don't give the calendar any events that shouldn't be shown. For example, rather than wiring the `events` attribute directly to your event store, wire it to a `computed` property that filters the events to only include the ones that fall within the current period. (And if you're querying events from your back end, just change the logic of which events you pull based on the user's current display period.) In the code, you can see an example of this sort of filtering in `findAndSortEventsInWeek`.

The calendar control passes back the dates you need for this filtering in the `headerProps` -- `periodStart` and `periodEnd`. Just keep in mind that `periodEnd` would be, in your example above, September 1, not August 31, which makes it easier to query when events have a time of day. 

This also gives you maximum flexibility to handle edge cases, such as what to do when multi-day events that cross over a visible month boundary -- for example, you could adjust their start/end date to truncate them and manually add the `continued`/`toBeContinued` classes to them so they look similar to when events wrap around a week.

Rather than filtering them out, you could use a similar computed/map approach to just style them differently based on your business logic--such as adding a class to change their transparency or background color when they are fully outside the display period. That might give you the best of both worlds.

Truncating events in the calendar control itself might be possible, but there are some potential issues, such as working out how to most reasonable handle dragging and dropping of events.
