### ISSUE TITLE
Customizing header: Working example missing

### ISSUE THREAD

**Issue by michaelscheurer** [richardtallent/vue-simple-calendar#85]
I'd like to customize the header. It's explained in the documentation, but unfortunately only in a more or less theoretical way. I'm strongly missing a working example. I tried to implement a simple header with two buttons (next month and previous month).

I'd be very happy for some help. I thought about doing it somehow like this (but couldn't get to work it)

`<span slot="header" slot-scope="slotProps">
   <button @click="onInput(slotProps.headerProps.previousPeriod)">previous</button >
   <button  @click="onInput(slotProps.headerProps.nextPeriod)">next</button >
</span>`

Thanks a lot for every hint.

**Comment by rohk** [comment]
I'm trying to do the same thing, and I think the periodLabel is missing in the slot props.
This is a computed property of the calendar view.

**Comment by richardtallent** [comment]
Sure, I'll see if I can come up with an example. The default header is a separate component, I've actually thought about making the header slot *required* in the next major version so people can use the sample code directly with their own header (and to help people who don't want a header at all).

You're correct that `periodLabel` is not passed in the slot props. However, the data used to compute it is, and the function `formattedPeriod ` that creates the label is in the `calendar-math` mix-in. So, you can just add that mix-in to your custom header and call it directly. I figured giving the raw data would provide more flexibility. I'm may revisit that in the future, since many custom headers seem to be more about having more control over the buttons rather than about rendering the label a different way.

**Comment by richardtallent** [comment]
Hi @michaelscheurer, just wanted to let you know this has been fixed, in a sense, in 4.0.2, just released.

Please be aware that **there are breaking changes** in this version. Perhaps most notably, now *all* calendars that want a header use the header slot, even if using the default header. So, you can use the sample application as a full example now of using the header slot, and you can use the default `CalendarViewHeader.vue` component as a template for making your own custom header.

Also, to @rohk's point, the `headerProps` now includes a `label` key containing the rendered period label that the default header uses. This allows any custom header to take advantage of the same label logic.
