### ISSUE TITLE
Hide sunday 

### ISSUE THREAD

**Issue by benjamin79** [richardtallent/vue-simple-calendar#86]
Hi,

thanks for the great component so far. Coming from FullCalendar. I´d like to hide sunday. Is this possible?

thanks

**Comment by richardtallent** [comment]
Thanks Benjamin!

There is no built-in option to hide a day of the week. The logic depends on a 7-day week, and since the calendar was designed around handling multi-day events, hiding days would create some user experience challenges.

That said, as long as you override some CSS and ensure none of your events include a Sunday, I believe it is possible to get what you're looking for.

The easy part is hiding the Sunday column, you just need a rule of `.dow0 { display:none; }`.

The harder part is making the events overlay a 6-column grid rather than a 7-column grid. For that, start by setting the `startingDayOfWeek` option to `1` so Sunday falls at the end of the week rather than the beginning. Then, create overriding CSS rules for `.cv-event.offset1` through `.cv-event.offset5` (`offset0` is still good and you won't need `offset6`) and `.cv-event.span1` through `.cv-event.span6` (`span7` will be unused) to all use a divisor of `6` rather than `7`.

Hope that helps!
