### ISSUE TITLE
Weekly Recurrence 

### ISSUE THREAD

**Issue by vibrates09** [richardtallent/vue-simple-calendar#88]
Hi! Good day.
Thanks for your effort on this plugin.

Is it possible if we add the startDate and endDate once
then add the days of the week it will occur.
For example
The startDate of a class will be on first week on august
then it will end at last week on December.
Then the day it occurs will be on MWF.

**Comment by richardtallent** [comment]
Hi, and thank you!

I think one of the beautiful things about Vue's "way" is that good components don't try to determine their own state, they merely show what is given to them. So that's how I try to engineer my components -- taking in props, presenting them nicely, and emitting (hopefully) useful events that the developer can respond to.

So, applied to a calendar control, the calendar component here merely displays the events *you* give it, rather than trying to filter, repeat, or otherwise interpret them (other than some defaulting of missing event properties).

If I were to try to create a calendar control that covered *everyone's* use cases for repeating events, I would fail miserably. There are too many potential business rules -- repeats based on days of the week, days of the month, day intervals, astronomical events, etc.

Fortunately, it's fairly trivial to do this yourself, and then pass in the *resulting* events "pre-repeated" to the calendar's `events` prop.

For example, this function will take any event, a start and end date (which should be the current date range shown on the calendar), and an array of days of the week you want to repeat on (0 = Sunday, etc.), and will return an array of repeated events between `startDate` and `endDate`. You'll of course need to add unique event IDs and have some way for your logic to recognize the "original" event when the user clicks on one of the repeats.

```
function getRepeatedEventsBetween(event, startDate, endDate, repeatsOnDays) {
  const numDays = (endDate - startDate) / 86400000
  return [...Array(numDays).keys()]
    .map(d => new Date(startDate.getFullYear(), startDate.getMonth(), startDate.getDate() + d))
    .filter(d => repeatsOnDays.includes(d.getDay()))
    .map(d => ({...event, startDate: d, endDate: d }))
}

...
// Calling it to generate repeated events this month on Mondays, Wednesdays,
// and Fridays looks something like this:
const myRepeatedEvents = getRepeatedEventsBetween({ title: "FUN DAY!" }, new Date(2018,7,1), new Date(2018,8,1), [1,3,5])
```

The above could be optimized a bit, I aimed more for clarity than sheer performance. It creates an array of dates between the start and end date, filters to only include the ones falling on the days of the week you want, and then maps those dates onto the template event to generate a new event array.

**Comment by vibrates09** [comment]
You are amazing sir! Thanks for your feedback
