### ISSUE TITLE
[Feature Request] Add a class to related event blocks on hover

### ISSUE THREAD

**Issue by Dylan-Chapman** [richardtallent/vue-simple-calendar#95]
It'd be nice if there was a class for related `.toBeContinued` and `.continued` elements when they were hovered over. This way, we could add hover styling (i.e. color change) to all of the blocks when hovering over a single one. Right now, it's kind of aesthetically weird when half of the total event has hover styling applied and the other half doesn't.

**Comment by richardtallent** [comment]
Agreed.

I think this would be the right path for the code:
- Add a `data` element `currentHoveredEventId` to store the ID of the currently-hovered event.
- Add `@mouseenter`/`@mouseleave` event handlers to manage that element (this means this enhancement won't work for those using slots for events).
- Modify `normalizeEvent()` in the mix-in to take a new boolean argument to decide if the hover class is applied (I'd suggest the class name `isHovered`).
- Modify `fixedEvents()` so it uses `currentHoveredEventId` (setting up the reactivity) and passes the true/false result to `normalizeEvent()` (thus changing the event source used for drawing all copies of that event on the control, regardless how many weeks it spans). Since I'm using `map()` here, that means either replacing it with `for`, or adding another function layer. Not a bit deal either way.

This should be straightforward and a good candidate for the next version.

**Comment by Dylan-Chapman** [comment]
Just to add on, it's basically the same for people using events in slots. Here's what I did based off of @richardtallent's response:

- Added `idHoveredEvent: null` to my component data
- On event `@mouseenter`, set `this.idHoveredEvent = event.id`
- On event `@mouseleave`, set `this.idHoveredEvent = null`
- Added a class to the event: `"cv-event--hovered": event.id === this.idHoveredEvent`
- Add styling for `.cv-event--hovered`

**Comment by richardtallent** [comment]
This new functionality has been added to the latest version, 4.1.0.
